M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Sat Oct  3 07:13:53 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-03T07:13:53+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X125.3Y-56.1
X125.3Y-148.1
X167.3Y-56.1
X167.3Y-148.1
M30
